import { Permission as PrismaPermission, Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';

// Default permissions per built-in workspace role
// Keep this in sync with prisma/scripts/seed-default-permissions.ts
export const defaultRolePermissions: Record<string, PrismaPermission[]> = {
  OWNER: [
    'CREATE_POST','EDIT_SELF_POST','EDIT_ANY_POST','DELETE_SELF_POST','DELETE_ANY_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','EDIT_ANY_COMMENT','DELETE_SELF_COMMENT','DELETE_ANY_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','CREATE_TASK','EDIT_SELF_TASK','EDIT_ANY_TASK','DELETE_SELF_TASK','DELETE_ANY_TASK','ASSIGN_TASK','VIEW_TASKS','CHANGE_TASK_STATUS','CREATE_BOARD','EDIT_BOARD','DELETE_BOARD','MANAGE_BOARD_SETTINGS','VIEW_BOARDS','MANAGE_WORKSPACE_SETTINGS','MANAGE_WORKSPACE_MEMBERS','MANAGE_WORKSPACE_PERMISSIONS','VIEW_WORKSPACE_ANALYTICS','INVITE_MEMBERS','REMOVE_MEMBERS','CHANGE_MEMBER_ROLES','VIEW_MEMBER_LIST','MANAGE_INTEGRATIONS','EXPORT_DATA','IMPORT_DATA','VIEW_AUDIT_LOGS','CREATE_FEATURE_REQUEST','EDIT_SELF_FEATURE_REQUEST','EDIT_ANY_FEATURE_REQUEST','DELETE_SELF_FEATURE_REQUEST','DELETE_ANY_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_EPIC','EDIT_SELF_EPIC','EDIT_ANY_EPIC','DELETE_SELF_EPIC','DELETE_ANY_EPIC','VIEW_EPICS','CREATE_STORY','EDIT_SELF_STORY','EDIT_ANY_STORY','DELETE_SELF_STORY','DELETE_ANY_STORY','VIEW_STORIES','CREATE_MILESTONE','EDIT_SELF_MILESTONE','EDIT_ANY_MILESTONE','DELETE_SELF_MILESTONE','DELETE_ANY_MILESTONE','VIEW_MILESTONES','CREATE_NOTE','EDIT_SELF_NOTE','EDIT_ANY_NOTE','DELETE_SELF_NOTE','DELETE_ANY_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE','DELETE_ANY_MESSAGE','COMMENT_ON_TASK','MANAGE_NOTIFICATIONS','VIEW_REPORTS','PIN_POST','RESOLVE_BLOCKER','MANAGE_LEAVE'
  ] as PrismaPermission[],
  ADMIN: [
    'CREATE_POST','EDIT_SELF_POST','EDIT_ANY_POST','DELETE_SELF_POST','DELETE_ANY_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','EDIT_ANY_COMMENT','DELETE_SELF_COMMENT','DELETE_ANY_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','CREATE_TASK','EDIT_SELF_TASK','EDIT_ANY_TASK','DELETE_SELF_TASK','DELETE_ANY_TASK','ASSIGN_TASK','VIEW_TASKS','CHANGE_TASK_STATUS','CREATE_BOARD','EDIT_BOARD','DELETE_BOARD','MANAGE_BOARD_SETTINGS','VIEW_BOARDS','MANAGE_WORKSPACE_MEMBERS','MANAGE_WORKSPACE_PERMISSIONS','VIEW_WORKSPACE_ANALYTICS','INVITE_MEMBERS','REMOVE_MEMBERS','CHANGE_MEMBER_ROLES','VIEW_MEMBER_LIST','MANAGE_INTEGRATIONS','EXPORT_DATA','VIEW_AUDIT_LOGS','CREATE_FEATURE_REQUEST','EDIT_SELF_FEATURE_REQUEST','EDIT_ANY_FEATURE_REQUEST','DELETE_SELF_FEATURE_REQUEST','DELETE_ANY_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_EPIC','EDIT_SELF_EPIC','EDIT_ANY_EPIC','DELETE_SELF_EPIC','DELETE_ANY_EPIC','VIEW_EPICS','CREATE_STORY','EDIT_SELF_STORY','EDIT_ANY_STORY','DELETE_SELF_STORY','DELETE_ANY_STORY','VIEW_STORIES','CREATE_MILESTONE','EDIT_SELF_MILESTONE','EDIT_ANY_MILESTONE','DELETE_SELF_MILESTONE','DELETE_ANY_MILESTONE','VIEW_MILESTONES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE','COMMENT_ON_TASK','MANAGE_NOTIFICATIONS','VIEW_REPORTS','PIN_POST','RESOLVE_BLOCKER'
  ] as PrismaPermission[],
  MODERATOR: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','CREATE_TASK','EDIT_SELF_TASK','EDIT_ANY_TASK','DELETE_SELF_TASK','ASSIGN_TASK','VIEW_TASKS','CHANGE_TASK_STATUS','CREATE_BOARD','EDIT_BOARD','MANAGE_BOARD_SETTINGS','VIEW_BOARDS','VIEW_WORKSPACE_ANALYTICS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','EDIT_SELF_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_EPIC','EDIT_SELF_EPIC','EDIT_ANY_EPIC','DELETE_SELF_EPIC','VIEW_EPICS','CREATE_STORY','EDIT_SELF_STORY','EDIT_ANY_STORY','DELETE_SELF_STORY','VIEW_STORIES','CREATE_MILESTONE','EDIT_SELF_MILESTONE','EDIT_ANY_MILESTONE','DELETE_SELF_MILESTONE','VIEW_MILESTONES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE','COMMENT_ON_TASK','VIEW_REPORTS','RESOLVE_BLOCKER'
  ] as PrismaPermission[],
  DEVELOPER: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','CREATE_TASK','EDIT_SELF_TASK','DELETE_SELF_TASK','ASSIGN_TASK','VIEW_TASKS','CHANGE_TASK_STATUS','VIEW_BOARDS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','EDIT_SELF_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_EPIC','EDIT_SELF_EPIC','DELETE_SELF_EPIC','VIEW_EPICS','CREATE_STORY','EDIT_SELF_STORY','DELETE_SELF_STORY','VIEW_STORIES','CREATE_MILESTONE','EDIT_SELF_MILESTONE','DELETE_SELF_MILESTONE','VIEW_MILESTONES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE','COMMENT_ON_TASK'
  ] as PrismaPermission[],
  PROJECT_MANAGER: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','CREATE_TASK','EDIT_SELF_TASK','EDIT_ANY_TASK','DELETE_SELF_TASK','ASSIGN_TASK','VIEW_TASKS','CHANGE_TASK_STATUS','CREATE_BOARD','EDIT_BOARD','VIEW_BOARDS','VIEW_WORKSPACE_ANALYTICS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','EDIT_SELF_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_EPIC','EDIT_SELF_EPIC','EDIT_ANY_EPIC','DELETE_SELF_EPIC','VIEW_EPICS','CREATE_STORY','EDIT_SELF_STORY','EDIT_ANY_STORY','DELETE_SELF_STORY','VIEW_STORIES','CREATE_MILESTONE','EDIT_SELF_MILESTONE','EDIT_ANY_MILESTONE','DELETE_SELF_MILESTONE','VIEW_MILESTONES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE','COMMENT_ON_TASK','VIEW_REPORTS','PIN_POST','RESOLVE_BLOCKER'
  ] as PrismaPermission[],
  DESIGNER: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','CREATE_TASK','EDIT_SELF_TASK','DELETE_SELF_TASK','VIEW_TASKS','CHANGE_TASK_STATUS','VIEW_BOARDS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','EDIT_SELF_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_STORY','EDIT_SELF_STORY','DELETE_SELF_STORY','VIEW_STORIES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE','COMMENT_ON_TASK'
  ] as PrismaPermission[],
  QA_TESTER: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','CREATE_TASK','EDIT_SELF_TASK','DELETE_SELF_TASK','VIEW_TASKS','CHANGE_TASK_STATUS','VIEW_BOARDS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','EDIT_SELF_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE','COMMENT_ON_TASK'
  ] as PrismaPermission[],
  CONTENT_CREATOR: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','VIEW_TASKS','VIEW_BOARDS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE'
  ] as PrismaPermission[],
  ANALYST: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','VIEW_TASKS','VIEW_BOARDS','VIEW_WORKSPACE_ANALYTICS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','EDIT_SELF_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE','VIEW_REPORTS'
  ] as PrismaPermission[],
  HR: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','VIEW_TASKS','VIEW_BOARDS','VIEW_WORKSPACE_ANALYTICS','VIEW_MEMBER_LIST','INVITE_MEMBERS','CHANGE_MEMBER_ROLES','CREATE_FEATURE_REQUEST','EDIT_SELF_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE','MANAGE_NOTIFICATIONS','VIEW_REPORTS','PIN_POST'
  ] as PrismaPermission[],
  MARKETING: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','VIEW_TASKS','VIEW_BOARDS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE'
  ] as PrismaPermission[],
  SALES: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','VIEW_TASKS','VIEW_BOARDS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE'
  ] as PrismaPermission[],
  CUSTOMER_SUPPORT: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','VIEW_TASKS','VIEW_BOARDS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE'
  ] as PrismaPermission[],
  MEMBER: [
    'CREATE_POST','EDIT_SELF_POST','DELETE_SELF_POST','COMMENT_ON_POST','EDIT_SELF_COMMENT','DELETE_SELF_COMMENT','REACT_TO_POST','REACT_TO_COMMENT','MENTION_USERS','VIEW_POSTS','BOOKMARK_POST','CREATE_TASK','EDIT_SELF_TASK','DELETE_SELF_TASK','VIEW_TASKS','CHANGE_TASK_STATUS','VIEW_BOARDS','VIEW_MEMBER_LIST','CREATE_FEATURE_REQUEST','EDIT_SELF_FEATURE_REQUEST','VOTE_ON_FEATURE','COMMENT_ON_FEATURE','VIEW_FEATURES','CREATE_NOTE','EDIT_SELF_NOTE','DELETE_SELF_NOTE','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES','DELETE_SELF_MESSAGE','COMMENT_ON_TASK'
  ] as PrismaPermission[],
  VIEWER: [
    'VIEW_POSTS','REACT_TO_POST','REACT_TO_COMMENT','BOOKMARK_POST','VIEW_TASKS','VIEW_BOARDS','VIEW_MEMBER_LIST','VOTE_ON_FEATURE','VIEW_FEATURES','VIEW_NOTES','SEND_MESSAGE','VIEW_MESSAGES'
  ] as PrismaPermission[],
  GUEST: [
    'VIEW_POSTS','VIEW_TASKS','VIEW_BOARDS','VIEW_MEMBER_LIST','VOTE_ON_FEATURE','VIEW_FEATURES'
  ] as PrismaPermission[],
};

export async function ensureRolePermissionsForWorkspaceRole(
  workspaceId: string,
  role: string
): Promise<void> {
  const existingCount = await prisma.rolePermission.count({
    where: { workspaceId, role },
  });
  if (existingCount > 0) return;

  const permissions = defaultRolePermissions[role];
  if (!permissions || permissions.length === 0) return;

  await prisma.rolePermission.createMany({
    data: permissions.map((permission) => ({
      workspaceId,
      role,
      permission,
    })),
    skipDuplicates: true,
  });
}


