-- AlterTable
ALTER TABLE "User" ADD COLUMN     "avatarAccessory" INTEGER DEFAULT 0,
ADD COLUMN     "avatarBrows" INTEGER DEFAULT 1,
ADD COLUMN     "avatarEyes" INTEGER DEFAULT 1,
ADD COLUMN     "avatarEyewear" INTEGER DEFAULT 0,
ADD COLUMN     "avatarHair" INTEGER DEFAULT 1,
ADD COLUMN     "avatarMouth" INTEGER DEFAULT 1,
ADD COLUMN     "avatarNose" INTEGER DEFAULT 1,
ADD COLUMN     "avatarSkinTone" INTEGER DEFAULT 1,
ADD COLUMN     "useCustomAvatar" BOOLEAN NOT NULL DEFAULT false;
