name: Auto add contributors to README

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: read

jobs:
  add-contributor:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure README has All Contributors anchors
        run: |
          if [ ! -f README.md ]; then
            echo "# ${GITHUB_REPOSITORY##*/}" > README.md
          fi
          if ! grep -q "ALL-CONTRIBUTORS-LIST:START" README.md; then
            cat << 'EOF' >> README.md

## Contributors ✨
Thanks goes to these wonderful people ([emoji key](https://allcontributors.org/docs/en/emoji-key)):

<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- ALL-CONTRIBUTORS-LIST:END -->

This project follows the [all-contributors](https://github.com/all-contributors/all-contributors) specification.
EOF
          fi

      - name: Create default .all-contributorsrc if missing
        run: |
          if [ ! -f .all-contributorsrc ]; then
            cat << 'JSON' > .all-contributorsrc
{
  "projectName": "${GITHUB_REPOSITORY##*/}",
  "projectOwner": "${GITHUB_REPOSITORY%/*}",
  "repoType": "github",
  "repoHost": "https://github.com",
  "files": ["README.md"],
  "imageSize": 100,
  "commit": false,
  "contributors": [],
  "contributorsPerLine": 7,
  "badgeTemplate": "",
  "skipCi": true
}
JSON
          fi

      - name: Install all-contributors-cli
        run: npm i -g all-contributors-cli

      - name: Decide contribution type(s)
        id: types
        shell: bash
        run: |
          # Vars
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS_JSON='${{ toJson(github.event.pull_request.labels) }}'

          # Default = code
          TYPES="code"

          # If PR has certain labels, adjust types
          echo "$LABELS_JSON" | grep -qi '"name":"docs"' && TYPES="doc"
          echo "$LABELS_JSON" | grep -qi '"name":"documentation"' && TYPES="doc"
          echo "$LABELS_JSON" | grep -qi '"name":"design"' && TYPES="design"
          echo "$LABELS_JSON" | grep -qi '"name":"bugfix"' && TYPES="bug,code"

          echo "types=$TYPES" >> $GITHUB_OUTPUT

      - name: Add PR author as contributor
        env:
          AUTHOR_LOGIN: ${{ github.event.pull_request.user.login }}
          TYPES: ${{ steps.types.outputs.types }}
        run: |
          echo "Adding @$AUTHOR_LOGIN for: $TYPES"
          # Add (idempotent; CLI atlama yapar, duplicate yazmaz)
          npx all-contributors add "$AUTHOR_LOGIN" "$TYPES" || true
          # Re-generate README
          npx all-contributors generate

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md .all-contributorsrc || true
          git commit -m "docs: add @${{ github.event.pull_request.user.login }} as contributor [skip ci]" || echo "No changes to commit"
          git push || true
